services:
  - type: web
    name: brief
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 8 --timeout 1000 app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: BRIEF_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
